apiVersion : apps/v1
kind: Deployment
metadata:
  name: "exaiotaks-2636"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "exaiotaks-2636"
  template:
    metadata:
      labels:
        app: "exaiotaks-2636"
    spec:
      containers:
        - name: "exaiotaks-2636"
          image: "exaiotconregistryargocd.azurecr.io/exaiotaks"
          ports:
          - containerPort: 80